### ISSUE TITLE
Unable to slice STL files with Version 1.1.1 - after changing str(int(f)) to to_unicode(int(f)) File:profile.py Line:745

### ISSUE THREAD

**Issue by aminutolo** [OctoPrint/OctoPrint-CuraEngineLegacy#8]
The following occurs when using OctaPi 0.17.0/OctaPrint 1.3.12 with the 1.1.1 plugin. Attempted to slice an STL file to prepare for printing when this occurred. 

2020-12-04 01:03:25,283 - octoprint.plugins.tracking - INFO - Sent tracking event slicing_started, payload: {'slicer': u'curalegacy'}
2020-12-04 01:03:26,654 - octoprint.plugins.curalegacy - ERROR - Could not slice via Cura, got an unknown error
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_curalegacy/__init__.py", line 330, in do_slice
    used_extruders=1)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_curalegacy/__init__.py", line 511, in _convert_to_engine
    return profile.convert_to_engine(used_extruders=used_extruders)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_curalegacy/profile.py", line 932, in convert_to_engine
    "endCode": self.get_gcode("end_gcode", extruder_count=actual_extruder_count),
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_curalegacy/profile.py", line 767, in get_gcode
    + '\n' + postfix).strip() + '\n'
  File "/home/pi/oprint/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_curalegacy/profile.py", line 745, in replaceTagMatch
    return pre + to_unicode(int(f))
TypeError: coercing to Unicode: need string or buffer, int found

Log also attached.
[octoprint (1).log](https://github.com/OctoPrint/OctoPrint-CuraEngineLegacy/files/5642917/octoprint.1.log)

**Comment by markwal** [comment]
It looks like your start.gcode in the profile may have something that looks like: F{travel_speed} or one of the other speeds print_speed, max_z_speed, retraction_speed, bottom_layer_speed or cool_min_feedrate.  It would be handy to have your cura.ini to make sure I've fixed it.

**Comment by markwal** [comment]
@aminutolo I'm having trouble reproducing this.  OctoPrint's to_unicode function checks to make sure the passed in element is a string before coercing it to unicode, so I'm confused about what is happening for you and can't reproduce here, yet.

I'm running Python 3 and OctoPrint 1.5.2.  How about you?  Perhaps you've got an earlier version of to_unicode that I'm not seeing.

**Comment by markwal** [comment]
@aminutolo I also tried under Python 2.  My start gcode had substitutions for print_bed_temperature, print_temperature and travel_speed.  All three hit the code in question and pass no problem (I put in a log to make sure).  I think I'm going to need your start/end gcode and/or the slicing profile to reproduce.

**Comment by markwal** [comment]
Oh.  Hang on.  You gave the OctoPrint version up there: 1.3.12.  I'll check that version.

**Comment by markwal** [comment]
Yes.  It turns out that version 1.1.1 relies on a to_unicode behavior of coercing the argument to string before conversion.  That behavior was introduces in OctoPrint 1.4.0, therefore, version 1.1.1 of this plugin requires at least version 1.4.0 of OctoPrint (and probably later, TBH)
